deployment:
  tasks:
    - composer install --optimize-autoloader --no-dev
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - npm install
    - npm run build